export const positions = [
  "Business Analyst",
  "Test Engineer",
  "Graphic Designer",
  "Quality Assurance Manual",
  "Programator Sistem Informatic",
  "Graduate Diploma Intern",
  "Senior Business Analyst",
  ".NET Web Developer",
  "Junior Software Engineer",
  "PHP Software Engineer",
  "Java  Developer",
  "Analist Vanzari",
  "Senior Software Developer",
  "Project Administrator",
  "SAP Consultant",
  "Jsd2",
  "Senior Embedded Software Developer",
  "Frontend Developer",
  "Developer",
  "Junior Technical Support Engineer",
  "Senior PHP Developer",
  "Android",
  "Proiectant",
  "Tester",
  "Software Development Engineer",
  "iOS Developer",
  "Scrum Master",
  "Technical Consultant",
  "Software Developer Intern",
  "Oracle Analyst",
  "Junior IT Consultant",
  "Technical Support Specialist",
  "Middle Software Tester",
  "Principal QA",
  "System Engineer",
  "Software Developer - Part-time 4 Ore",
  "Automation Tester",
  "Team Leader",
  ".NET Developer",
  "Middle System Administrator",
  "Junior Java Programmer",
  "QA Tester Software",
  "Application Management Specialist",
  "Front End Developer",
  "Junior QA Automation",
  "Ajutor Programator",
  "Junior Developer",
  "Software Developer",
  "Associate Quality Assurence Engineer",
  "Digital Design Engineer",
  "Project Engineer",
  "Database Developer",
  "QA Test Lead",
  "B2b Support",
  "Specialist Marketing",
  "Senior Java Developer",
  "Tehnical Manager",
  "QA Automation Engineer",
  "SAP Key User",
  "Programator ABAP",
  "Software Engineering",
  "Product Tester",
  "Backend Software Developer",
  "Automation Student",
  "Software Project Manager",
  "Software Engineer",
  "Sysadmin",
  "QA Engineer",
  "Solution Architect",
  "Senior Java Developer ",
  "Software Engineer Intern",
  "UX Designer",
  "Software Engineering Senior Analyst",
  "Quality Engineer",
  "Junior Pl/sql Developer",
  "Data Analytics Engineer",
  "Studio Manager",
  "Inginer De Sistem In Informatica",
  "Data Analyst",
  "Java Graduate",
  "SAP Fi Consultant",
  "Programator",
  "Analist Programator",
  "Ofiter Bancar",
  "Java Senior Developer",
  "Tehnician IT",
  "Software Architect",
  "HR Manager",
  "Software Engineer 2",
  "IT Consultant",
  "Tehnician Debug",
  "Junior",
  "Big Data Java Engineer",
  "Analyst Crm",
  "Senior QA Automation ",
  "See Information Security Technical Sales",
  "PHP Developer",
  "Software Tesrer",
  "Test Automation",
  "Software Tester",
  "Programator SQL",
  "Web Builder",
  "QA",
  "Tech Lead",
  "Associate IT Consultant",
  "Administrator Retele",
  "Senior Systems Administrator",
  "Sw Test Engineer / Devops",
  "Tehnician",
  "Virtual Sysadmin",
  "C++ Developer",
  "Senior Frontend Developer",
  "Programator Junior",
  "Field Sysadmin",
  "Senior Software Tester",
  "Middle Software Developer",
  "Middle Software Engineer",
  "Back Office Engineer",
  "Software Integrator",
  "Specialist Dmarketing Digital",
  "Web Designer",
  "ABAP Developer",
  "Senior QA",
  "Software Engineering Associate",
  "Software Developer Trainee",
  "Java Developer",
  "Call Center Operator",
  "System Administrator",
  "Grup Leader",
  "Technical Writer",
  "IT Intern",
  "Test Manager ",
  "PHP Developer Intern",
  "Sw Project Manager",
  "Hardware Administator",
  "Ui UX Designer",
  "IT Supervisor",
  "SAP Sd Consultant",
  "Android Developer",
  "Hardware Developer",
  "Embedded Software Developer",
  "Junior PHP Developer",
  "Associate IT Consultan",
  "Junior Network Administrator",
  "Infrastructure Specialist",
  "Service Desk Analyst",
  "Technical Support Analyst",
  "Java",
  "Junior Java Developer",
  "Junior Web Developer",
  "Intern SAP ABAP Part Time",
  "Product Owner",
  "Senior Software Engineer",
  "Intern Java",
  "Network Supervisor - Noc",
  "Programator PHP",
  "Hardware Manager",
  "Mechanical Designer",
  "Devops",
  "Front Office Engineer",
  "IT Project Manager",
  "QA Automation",
  "C# Developer",
  "Senior Application Management Engineer",
  "Technical Lead",
  "IT System Administrator",
  "Java  Developer Jd2-3",
  "Senior Javascript Developer",
  "Junior Android Developer",
  "Global Service Desk - Support Analyst",
  "Junior Software Developer",
  "Web Developer",
  "Ap Accountant Senior",
  "Dwh Developer",
  "Junior Ui Developer",
  "Java Junior Developer",
  "Sw Developer 2",
  "Inginer",
  "Unity Developer",
  "Planning And Design Engineer",
  "Graphic Analyst",
  "Junior Cobol Developer",
  "Sw Developer",
  "Junior Software Developer - Part Time",
  "Software Engineering Analyst",
  "Business Intelligence Project Manager",
  "Project Manager",
  "Nmc Engineer",
  "Team Manager",
  "Senior Engineer Auto",
  "Junior Javascript Developer",
  "Intern",
  "Consultant",
  "Software Developer Junior",
  "Technical Service Manager",
  "Junior Developer - Part Time",
  "Agent Servicii Clienti",
  "Test Analyst",
  "Software Developer Intern - Part-time 4 Ore",
  "Senior Developer",
  "Coldfusion Developer",
  "Java Application Developer",
  "Junior Software Tester",
  "Quality Assurance",
  "Quality Assurance - Box Product",
  "Associate Technical Writer",
  "Baze De Date",
  "Associate Configuration Specialist",
  "Software Verification Engineer",
  "Software Engineer In Test",
  "Java Intern",
  "Technical Support Engineer I",
  "Incident Controller",
  "Helpdesk Technician",
  "Development Consultant",
  "Order Management",
  "Full Stack Developer",
  "HR",
  "Game Tester",
  "Senior Technical Support Engineer",
  "Programator Senior",
  "Junior Cobol Developer-intern",
  "Associate Development Consultant",
  "No Idea",
  "QA Tester",
  "QA Tester Ws",
  "Senior Web Developer",
  "Intern QA",
  "Customer Support",
  "Customer Development Specialist",
  "Senior Windows System Administrator",
];

export const cities = [
  "Satu Mare",
  "Pitesti",
  "Targu Mures",
  "Timisoata",
  "Petrosani",
  "Timisoara",
  "Bucuresti",
  "Cluj",
  "Miercurea Ciuc",
  "Galati",
  "Iasi",
  "Cluj-Napoca",
  "Cluj Napoca",
  "Bucharest",
  "Brasov",
  "Toata Tara",
  "Craiova",
  "Blaj",
  "Constanta",
  "Suceava",
  "Oradea",
  "Alba Iulia",
  "Sibiu",
];
